import { attachImages } from "./images";
import type { Category, MenuData, Product } from "./types";

const rawMenu: {
  categories: Category[];
  products: Array<Omit<Product, "image"> & { image?: string }>;
} = {
  categories: [
    {
      id: "cat-promos",
      name: "Promociones",
      slug: "promociones",
      description: "Combos de rolls para compartir.",
      note: "Incluye palitos, soya y agridulce.",
      kind: "menu",
      order: 1,
    },
    {
      id: "cat-premium",
      name: "Promos Premium",
      slug: "promos-premium",
      description: "Promos con extras y cortes especiales.",
      note: "Incluye palitos, soya y agridulce.",
      kind: "menu",
      order: 2,
    },
    {
      id: "cat-casa",
      name: "Rolls de la casa",
      slug: "rolls-de-la-casa",
      description: "Rolls especiales del local.",
      note: "Incluye palitos, soya y agridulce.",
      kind: "menu",
      order: 3,
    },
    {
      id: "cat-wraps",
      name: "Envolturas",
      slug: "envolturas",
      description: "Elige 1 envoltura. Define el precio del roll.",
      note: "Rolls a tu elección. Incluye palitos, soya y agridulce.",
      kind: "wrap",
      order: 3,
    },
    {
      id: "cat-wraps-premium",
      name: "Envolturas Premium",
      slug: "envolturas-premium",
      description: "Envolturas premium para rolls a tu elección.",
      note: "",
      kind: "wrap_premium",
      order: 4,
    },
    {
      id: "cat-sin-arroz",
      name: "Rolls sin arroz",
      slug: "rolls-sin-arroz",
      description: "1 envoltura + 1 proteína + 3 rellenos.",
      note: "Precio fijo $7.500.",
      kind: "menu",
      order: 5,
    },
    {
      id: "cat-proteinas",
      name: "Proteínas",
      slug: "proteinas",
      description: "Elige 1 proteína para tu roll.",
      note: "Incluida en el precio de la envoltura.",
      kind: "protein",
      order: 6,
    },
    {
      id: "cat-rellenos",
      name: "Rellenos",
      slug: "rellenos",
      description: "Elige 2 rellenos (3 si es sin arroz).",
      note: "Champiñón tiene recargo.",
      kind: "filling",
      order: 7,
    },
    {
      id: "cat-snack",
      name: "Snack",
      slug: "snack",
      description: "",
      note: "",
      kind: "menu",
      order: 8,
    },
    {
      id: "cat-apanados",
      name: "Apanados en panko",
      slug: "apanados",
      description: "6 unidades.",
      note: "",
      kind: "menu",
      order: 1,
      parentId: "cat-snack",
    },
    {
      id: "cat-hosomaki",
      name: "Hosomaki",
      slug: "hosomaki",
      description: "8 cortes.",
      note: "",
      kind: "menu",
      order: 2,
      parentId: "cat-snack",
    },
    {
      id: "cat-nigiri",
      name: "Nigiri",
      slug: "nigiri",
      description: "4 unidades.",
      note: "",
      kind: "menu",
      order: 3,
      parentId: "cat-snack",
    },
    {
      id: "cat-temaki",
      name: "Temaki",
      slug: "temaki",
      description: "Cono envuelto en nori.",
      note: "",
      kind: "menu",
      order: 4,
      parentId: "cat-snack",
    },
    {
      id: "cat-primavera",
      name: "Arrollados primavera",
      slug: "arrollados-primavera",
      description: "6 unidades.",
      note: "",
      kind: "menu",
      order: 5,
      parentId: "cat-snack",
    },
    {
      id: "cat-bowls",
      name: "Bowls",
      slug: "bowls",
      description: "",
      note: "",
      kind: "menu",
      order: 9,
    },
    {
      id: "cat-bowl",
      name: "Bowl",
      slug: "bowl",
      description: "Base de arroz. Elige 1 proteína y 4 vegetales: palta, pepino, zanahoria, tomate, cebollín, lechuga, palmito o champiñón.",
      note: "Champiñón puede tener recargo.",
      kind: "menu",
      order: 1,
      parentId: "cat-bowls",
    },
    {
      id: "cat-gohan",
      name: "Gohan",
      slug: "gohan",
      description:
        "Base de arroz de sushi acompañado de cebollín, queso crema, palta, camarones y trozos de salmón con un toque de sésamo mixto.",
      note: "",
      kind: "menu",
      order: 2,
      parentId: "cat-bowls",
    },
    {
      id: "cat-poke",
      name: "Poke Bowl",
      slug: "poke-bowl",
      description:
        "Base de arroz de sushi acompañado de cebollín, cubos de queso crema, palta y sésamo tostado.",
      note: "Elige 1 proteína. Incluye soya o agridulce.",
      kind: "menu",
      order: 10,
    },
    {
      id: "cat-papas",
      name: "Papas fritas",
      slug: "papas-fritas",
      description: "",
      note: "",
      kind: "menu",
      order: 14,
    },
    {
      id: "cat-bebidas",
      name: "Bebida individual",
      slug: "bebidas",
      description: "",
      note: "",
      kind: "menu",
      order: 15,
    },
    {
      id: "cat-jugos",
      name: "Jugo natural",
      slug: "jugos",
      description: "",
      note: "",
      kind: "menu",
      order: 16,
    },
    {
      id: "cat-extras",
      name: "Extras y cambios",
      slug: "extras",
      description: "Agregados, salsas y modificaciones.",
      note: "",
      kind: "extra",
      order: 17,
    },
  ],
  products: [
    {
      id: "promo-20",
      categoryId: "cat-promos",
      name: "Promo 20 cortes",
      description: "",
      price: 11000,
      extraPrice: 0,
      details: [
        "Pollo, queso crema, palta / PANKO",
        "Kanikama, queso crema, choclo / PALTA",
      ],
      available: true,
      featured: true,
      order: 1,
    },
    {
      id: "promo-30",
      categoryId: "cat-promos",
      name: "Promo 30 cortes",
      description: "",
      price: 16500,
      extraPrice: 0,
      details: [
        "Camarón, queso crema, palmito / PALTA",
        "Pollo, queso crema, palta / PANKO",
        "Kanikama, queso crema, morrón / QUESO CREMA",
      ],
      available: true,
      featured: false,
      order: 2,
    },
    {
      id: "promo-40",
      categoryId: "cat-promos",
      name: "Promo 40 cortes",
      description: "",
      price: 23000,
      extraPrice: 0,
      details: [
        "Pollo, queso crema, palta / PANKO",
        "Pollo, queso crema, choclo / PANKO",
        "Camarón, queso crema, morrón / PALTA",
        "Camarón, palmito, palta / QUESO CREMA",
      ],
      available: true,
      featured: false,
      order: 3,
    },
    {
      id: "promo-60",
      categoryId: "cat-promos",
      name: "Promo 60 cortes",
      description: "",
      price: 32000,
      extraPrice: 0,
      details: [
        "Pollo, queso crema, palta / PANKO",
        "Kanikama, queso crema, morrón / PANKO",
        "Camarón, palta, palmito / QUESO CREMA",
        "Salmón, queso crema, pepino / SÉSAMO MIXTO",
        "Pollo, queso crema, cebollín / PALTA",
        "Camarón, queso crema, choclo / TEMPURA",
      ],
      available: true,
      featured: true,
      order: 4,
    },
    {
      id: "promo-80",
      categoryId: "cat-promos",
      name: "Promo 80 cortes",
      description: "",
      price: 44000,
      extraPrice: 0,
      details: [
        "Pollo, queso crema, cebollín / JAMÓN SERRANO",
        "Pollo, queso crema, palta / PANKO",
        "Kanikama, queso crema, choclo / PANKO",
        "Salmón, queso crema, morrón / PALTA",
        "Camarón, queso crema, palta / CIBOULETTE",
        "Camarón, queso crema, pepino / QUESO CREMA",
        "Kanikama, queso crema, palta / TEMPURA",
        "Pollo, queso crema, aceituna / SÉSAMO MIXTO",
      ],
      available: true,
      featured: false,
      order: 5,
    },
    {
      id: "premium-18",
      categoryId: "cat-premium",
      name: "Promo 18 cortes + 4 panko balls",
      description: "",
      price: 12000,
      extraPrice: 0,
      details: [
        "Camarón apanado, queso crema, cebollín / PALTA",
        "8 cortes de hosomaki, kanikama, queso crema",
      ],
      available: true,
      featured: true,
      order: 1,
    },
    {
      id: "premium-30-panko",
      categoryId: "cat-premium",
      name: "Promo 30 cortes panko",
      description: "",
      price: 18000,
      extraPrice: 0,
      details: [
        "Pollo, queso crema, palta / PANKO",
        "Camarón, queso crema, palta / PANKO",
        "Salmón, queso crema, morrón / PANKO",
      ],
      available: true,
      featured: false,
      order: 2,
    },
    {
      id: "premium-30-cam",
      categoryId: "cat-premium",
      name: "Promo 30 cortes + 6 camarones apanados",
      description: "",
      price: 22000,
      extraPrice: 0,
      details: [
        "Salmón, queso crema, palta / PANKO",
        "Camarón, queso crema, ciboulette / PALTA",
        "Choclo, palta, palmito / QUESO CREMA",
      ],
      available: true,
      featured: false,
      order: 3,
    },
    {
      id: "premium-40",
      categoryId: "cat-premium",
      name: "Promo 40 cortes + 4 arrollados primavera",
      description: "",
      price: 25000,
      extraPrice: 0,
      details: [
        "Salmón, queso crema, morrón / QUESO CREMA",
        "Camarón, queso crema, choclo / PALTA",
        "Pollo, queso crema, palta / PANKO",
        "Camarón, queso crema, palmito / CIBOULETTE",
      ],
      available: true,
      featured: true,
      order: 4,
    },
    {
      id: "wrap-tempura",
      categoryId: "cat-wraps",
      name: "Tempura (frito)",
      description: "",
      price: 6500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 1,
    },
    {
      id: "wrap-panko",
      categoryId: "cat-wraps",
      name: "Panko (frito)",
      description: "",
      price: 6500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 2,
    },
    {
      id: "wrap-ciboulette",
      categoryId: "cat-wraps",
      name: "Ciboulette",
      description: "",
      price: 6500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 3,
    },
    {
      id: "wrap-queso",
      categoryId: "cat-wraps",
      name: "Queso crema",
      description: "",
      price: 6500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 4,
    },
    {
      id: "wrap-queso-merken",
      categoryId: "cat-wraps",
      name: "Queso crema merkén",
      description: "",
      price: 6800,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 5,
    },
    {
      id: "wrap-queso-sesamo",
      categoryId: "cat-wraps",
      name: "Queso crema sésamo",
      description: "",
      price: 6800,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 6,
    },
    {
      id: "wrap-palta",
      categoryId: "cat-wraps",
      name: "Palta",
      description: "",
      price: 6500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 7,
    },
    {
      id: "wrap-serrano",
      categoryId: "cat-wraps",
      name: "Jamón serrano",
      description: "",
      price: 6500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 8,
    },
    {
      id: "wrap-sesamo",
      categoryId: "cat-wraps",
      name: "Sésamo mixto tostado",
      description: "",
      price: 5800,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 9,
    },
    {
      id: "wrap-nori",
      categoryId: "cat-wraps",
      name: "Nori",
      description: "",
      price: 5500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 10,
    },
    {
      id: "wrap-nori-panko",
      categoryId: "cat-wraps",
      name: "Nori apanado en panko",
      description: "",
      price: 5800,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 11,
    },
    {
      id: "casa-gratinado",
      categoryId: "cat-casa",
      name: "Roll gratinado",
      description: "Panko, camarón y queso gratinado.",
      price: 7500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: true,
      order: 1,
    },
    {
      id: "casa-austral",
      categoryId: "cat-casa",
      name: "Roll Valle Austral",
      description: "Envoltura palta, camarón, salmón y queso crema.",
      price: 7500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 2,
    },
    {
      id: "casa-salmon",
      categoryId: "cat-casa",
      name: "Roll salmón",
      description: "Envoltura queso crema, topping salmón.",
      price: 7500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 3,
    },
    {
      id: "casa-camaron",
      categoryId: "cat-casa",
      name: "Roll camarón",
      description: "Envoltura queso crema, topping camarón.",
      price: 7500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 4,
    },
    {
      id: "wrap-qc-ciboulette",
      categoryId: "cat-wraps-premium",
      name: "Queso crema, ciboulette",
      description: "",
      price: 7000,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 1,
    },
    {
      id: "wrap-qc-almendra",
      categoryId: "cat-wraps-premium",
      name: "Queso crema, almendra",
      description: "",
      price: 7000,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 2,
    },
    {
      id: "wrap-salmon",
      categoryId: "cat-wraps-premium",
      name: "Salmón",
      description: "",
      price: 7000,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 3,
    },
    {
      id: "wrap-pistacho",
      categoryId: "cat-wraps-premium",
      name: "Queso pistacho",
      description: "",
      price: 7500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 4,
    },
    {
      id: "wrap-salmon-panko",
      categoryId: "cat-wraps-premium",
      name: "Salmón apanado en panko",
      description: "",
      price: 7500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 5,
    },
    {
      id: "wrap-mix-salmon",
      categoryId: "cat-wraps-premium",
      name: "Mix salmón palta",
      description: "",
      price: 7500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 6,
    },
    {
      id: "wrap-frutos",
      categoryId: "cat-wraps-premium",
      name: "Mix frutos secos",
      description: "",
      price: 8000,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 7,
    },
    {
      id: "sin-arroz",
      categoryId: "cat-sin-arroz",
      name: "Roll sin arroz",
      description: "Incluye 1 envoltura + 1 proteína + 3 rellenos.",
      price: 7500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 1,
    },
    {
      id: "prot-camaron",
      categoryId: "cat-proteinas",
      name: "Camarón",
      description: "",
      price: 0,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 1,
    },
    {
      id: "prot-pollo",
      categoryId: "cat-proteinas",
      name: "Pollo",
      description: "",
      price: 0,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 2,
    },
    {
      id: "prot-kanikama",
      categoryId: "cat-proteinas",
      name: "Kanikama",
      description: "",
      price: 0,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 3,
    },
    {
      id: "prot-salmon",
      categoryId: "cat-proteinas",
      name: "Salmón",
      description: "",
      price: 0,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 4,
    },
    {
      id: "prot-atun",
      categoryId: "cat-proteinas",
      name: "Atún",
      description: "",
      price: 0,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 5,
    },
    {
      id: "prot-champ",
      categoryId: "cat-proteinas",
      name: "Champiñón",
      description: "",
      price: 0,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 6,
    },
    {
      id: "rel-queso",
      categoryId: "cat-rellenos",
      name: "Queso crema",
      description: "",
      price: 0,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 1,
    },
    {
      id: "rel-cebollin",
      categoryId: "cat-rellenos",
      name: "Cebollín",
      description: "",
      price: 0,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 2,
    },
    {
      id: "rel-palmito",
      categoryId: "cat-rellenos",
      name: "Palmito",
      description: "",
      price: 0,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 3,
    },
    {
      id: "rel-morron",
      categoryId: "cat-rellenos",
      name: "Morrón",
      description: "",
      price: 0,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 4,
    },
    {
      id: "rel-palta",
      categoryId: "cat-rellenos",
      name: "Palta",
      description: "",
      price: 0,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 5,
    },
    {
      id: "rel-aceituna",
      categoryId: "cat-rellenos",
      name: "Aceituna",
      description: "",
      price: 0,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 6,
    },
    {
      id: "rel-choclo",
      categoryId: "cat-rellenos",
      name: "Choclo baby",
      description: "",
      price: 0,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 7,
    },
    {
      id: "rel-pepino",
      categoryId: "cat-rellenos",
      name: "Pepino",
      description: "",
      price: 0,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 8,
    },
    {
      id: "rel-ciboulette",
      categoryId: "cat-rellenos",
      name: "Ciboulette",
      description: "",
      price: 0,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 9,
    },
    {
      id: "rel-champ",
      categoryId: "cat-rellenos",
      name: "Champiñón",
      description: "Recargo extra",
      price: 0,
      extraPrice: 1200,
      details: [],
      available: true,
      featured: false,
      order: 10,
    },
    {
      id: "apa-salmon",
      categoryId: "cat-apanados",
      name: "Bastón de salmón",
      description: "6 unidades",
      price: 6000,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 1,
    },
    {
      id: "apa-camaron",
      categoryId: "cat-apanados",
      name: "Bastón camarón",
      description: "6 unidades",
      price: 6000,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 2,
    },
    {
      id: "apa-pollo",
      categoryId: "cat-apanados",
      name: "Bastón de pollo",
      description: "6 unidades",
      price: 5800,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 3,
    },
    {
      id: "apa-queso",
      categoryId: "cat-apanados",
      name: "Bastón queso crema",
      description: "6 unidades",
      price: 4200,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 4,
    },
    {
      id: "apa-balls-cam",
      categoryId: "cat-apanados",
      name: "Panko balls camarón, queso crema",
      description: "6 unidades",
      price: 4500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 5,
    },
    {
      id: "apa-balls-ceb",
      categoryId: "cat-apanados",
      name: "Panko balls queso crema, cebollín",
      description: "6 unidades",
      price: 4000,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 6,
    },
    {
      id: "hoso-camaron",
      categoryId: "cat-hosomaki",
      name: "Camarón, queso crema",
      description: "8 cortes",
      price: 3500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 1,
    },
    {
      id: "hoso-kani",
      categoryId: "cat-hosomaki",
      name: "Kanikama, queso crema",
      description: "8 cortes",
      price: 3000,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 2,
    },
    {
      id: "hoso-salmon",
      categoryId: "cat-hosomaki",
      name: "Salmón, queso crema",
      description: "8 cortes",
      price: 3500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 3,
    },
    {
      id: "hoso-palta",
      categoryId: "cat-hosomaki",
      name: "Palta, queso crema",
      description: "8 cortes",
      price: 3000,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 4,
    },
    {
      id: "nigiri-salmon",
      categoryId: "cat-nigiri",
      name: "Salmón",
      description: "4 unidades",
      price: 4500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 1,
    },
    {
      id: "nigiri-camaron",
      categoryId: "cat-nigiri",
      name: "Camarón",
      description: "4 unidades",
      price: 4500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 2,
    },
    {
      id: "temaki-salmon",
      categoryId: "cat-temaki",
      name: "Temaki de salmón",
      description: "Cono envuelto en nori, relleno salmón, queso crema, cebollín, apanado en panko.",
      price: 3300,
      extraPrice: 0,
      details: [],
      available: true,
      featured: true,
      order: 1,
    },
    {
      id: "primavera",
      categoryId: "cat-primavera",
      name: "Arrollados primavera",
      description: "6 unidades",
      price: 3000,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 1,
    },
    {
      id: "poke-salmon",
      categoryId: "cat-poke",
      name: "Salmón apanado",
      description: "",
      price: 5500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: true,
      order: 1,
    },
    {
      id: "poke-cam-apa",
      categoryId: "cat-poke",
      name: "Camarón apanado",
      description: "",
      price: 5500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 2,
    },
    {
      id: "poke-cam-salt",
      categoryId: "cat-poke",
      name: "Camarón salteado",
      description: "",
      price: 5500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 3,
    },
    {
      id: "poke-pollo",
      categoryId: "cat-poke",
      name: "Pollo apanado",
      description: "",
      price: 5000,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 4,
    },
    {
      id: "poke-kani",
      categoryId: "cat-poke",
      name: "Kanikama apanado",
      description: "",
      price: 4500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 5,
    },
    {
      id: "bowl-salmon",
      categoryId: "cat-bowl",
      name: "Salmón apanado",
      description: "",
      price: 7000,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 1,
    },
    {
      id: "bowl-cam-apa",
      categoryId: "cat-bowl",
      name: "Camarón apanado",
      description: "",
      price: 7000,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 2,
    },
    {
      id: "bowl-pollo",
      categoryId: "cat-bowl",
      name: "Pollo apanado",
      description: "",
      price: 6200,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 3,
    },
    {
      id: "bowl-cam-salt",
      categoryId: "cat-bowl",
      name: "Camarón salteado",
      description: "",
      price: 7000,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 4,
    },
    {
      id: "bowl-kani",
      categoryId: "cat-bowl",
      name: "Kanikama apanado",
      description: "",
      price: 6200,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 5,
    },
    {
      id: "gohan",
      categoryId: "cat-gohan",
      name: "Gohan",
      description: "Cebollín, queso crema, palta, camarones y trozos de salmón, con sésamo mixto.",
      price: 8000,
      extraPrice: 0,
      details: [],
      available: true,
      featured: true,
      order: 1,
    },
    {
      id: "papas",
      categoryId: "cat-papas",
      name: "Papas fritas",
      description: "",
      price: 3000,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 1,
    },
    {
      id: "papas-nuggets",
      categoryId: "cat-papas",
      name: "Papas fritas con nuggets",
      description: "",
      price: 4500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 2,
    },
    {
      id: "salchipapas",
      categoryId: "cat-papas",
      name: "Salchipapas",
      description: "",
      price: 4600,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 3,
    },
    {
      id: "coca",
      categoryId: "cat-bebidas",
      name: "Coca-Cola",
      description: "",
      price: 1300,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 1,
    },
    {
      id: "fanta",
      categoryId: "cat-bebidas",
      name: "Fanta",
      description: "",
      price: 1300,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 2,
    },
    {
      id: "sprite",
      categoryId: "cat-bebidas",
      name: "Sprite",
      description: "",
      price: 1300,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 3,
    },
    {
      id: "jugo-frutilla",
      categoryId: "cat-jugos",
      name: "Frutilla",
      description: "",
      price: 1600,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 1,
    },
    {
      id: "jugo-pina",
      categoryId: "cat-jugos",
      name: "Piña",
      description: "",
      price: 1600,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 2,
    },
    {
      id: "jugo-frambuesa",
      categoryId: "cat-jugos",
      name: "Frambuesa",
      description: "",
      price: 1600,
      extraPrice: 0,
      details: [],
      available: true,
      featured: true,
      order: 3,
    },
    {
      id: "ex-acevicha",
      categoryId: "cat-extras",
      name: "Acevicha tu rolls",
      description: "",
      price: 2500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 1,
    },
    {
      id: "ex-envoltura",
      categoryId: "cat-extras",
      name: "Cambia tu envoltura",
      description: "",
      price: 1000,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 2,
    },
    {
      id: "ex-prot-pollo",
      categoryId: "cat-extras",
      name: "Cambio de proteína: pollo",
      description: "",
      price: 1500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 3,
    },
    {
      id: "ex-prot-kani",
      categoryId: "cat-extras",
      name: "Cambio de proteína: kanikama",
      description: "",
      price: 800,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 4,
    },
    {
      id: "ex-prot-cam-sal",
      categoryId: "cat-extras",
      name: "Cambio de proteína: camarón o salmón",
      description: "",
      price: 1800,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 5,
    },
    {
      id: "ex-sin-nori",
      categoryId: "cat-extras",
      name: "Roll sin nori",
      description: "",
      price: 500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 6,
    },
    {
      id: "ex-prot-apa",
      categoryId: "cat-extras",
      name: "Proteína apanada",
      description: "",
      price: 500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 7,
    },
    {
      id: "ex-nori-panko",
      categoryId: "cat-extras",
      name: "Nori panko",
      description: "Cambio de envoltura snack",
      price: 500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 8,
    },
    {
      id: "ex-nori-tempura",
      categoryId: "cat-extras",
      name: "Nori tempura",
      description: "Cambio de envoltura snack",
      price: 500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 9,
    },
    {
      id: "ex-soya-pote",
      categoryId: "cat-extras",
      name: "Soya (pote)",
      description: "",
      price: 500,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 10,
    },
    {
      id: "ex-soya-sachet",
      categoryId: "cat-extras",
      name: "Soya (sachet)",
      description: "",
      price: 200,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 11,
    },
    {
      id: "ex-agridulce",
      categoryId: "cat-extras",
      name: "Agridulce",
      description: "",
      price: 800,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 12,
    },
    {
      id: "ex-merken",
      categoryId: "cat-extras",
      name: "Agridulce al merkén",
      description: "",
      price: 850,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 13,
    },
    {
      id: "ex-jengibre",
      categoryId: "cat-extras",
      name: "Jengibre",
      description: "",
      price: 400,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 14,
    },
    {
      id: "ex-wasabi",
      categoryId: "cat-extras",
      name: "Wasabi",
      description: "",
      price: 350,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 15,
    },
    {
      id: "ex-spicy",
      categoryId: "cat-extras",
      name: "Salsa spicy",
      description: "",
      price: 800,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 16,
    },
    {
      id: "ex-vino",
      categoryId: "cat-extras",
      name: "Salsa reducción de vino",
      description: "",
      price: 800,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 17,
    },
    {
      id: "ex-salsa-acevichada",
      categoryId: "cat-extras",
      name: "Salsa acevichada",
      description: "",
      price: 800,
      extraPrice: 0,
      details: [],
      available: true,
      featured: false,
      order: 18,
    },
  ],
};

export const seedMenu: MenuData = attachImages(rawMenu);
